---

- name: Add packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - nzbget
    - p7zip-full
    - unrar

- name: Create nzbget group
  group:
    name: nzbget
    state: present

- name: Create nzbget User
  user:
    name: nzbget
    shell: /bin/bash
    groups: nzbget
    append: yes

- name: Ensure nzbget directory exists and has correct permissions
  file:
    path: /opt/nzbget
    owner: nzbget
    group: nzbget
    state: directory
    recurse: yes

- name: Create nzbget service
  copy: src=nzbget.service dest=/etc/systemd/system/nzbget.service
  notify:
    - reload systemd
    - restart nzbget

- name: Copy nzbget configuration
  template:
    src: nzbget.conf
    dest: /opt/nzbget/nzbget.conf
    owner: nzbget
    group: nzbget
  notify:
    - restart nzbget

- name: Start nzbget
  systemd:
    name: nzbget
    enabled: yes
    state: started
