---

- name: Add sonarr key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: FDA5DFFC
    state: present

- name: Add sonarr repo
  apt_repository:
    repo: deb http://apt.sonarr.tv/ubuntu bionic main
    state: present

- name: Add mono key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 2009837CBFFD68F45BC180471F4F90DE2A9B4BF8
    state: present

- name: Add mono repo
  apt_repository:
    repo: deb https://download.mono-project.com/repo/ubuntu stable-bionic main
    state: present

- name: Add mediainfo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: C5CDF62C7AE05CC847657390C10E11090EC0E438
    state: present

- name: Add mediainfo repo
  apt:
    deb: https://mediaarea.net/repo/deb/repo-mediaarea_1.0-11_all.deb

- name: Add packages
  apt:
    name: 'sonarr'
    state: present
    update_cache: yes

- name: Start sonarr
  systemd:
    name: sonarr
    enabled: yes
    state: started
