#!/bin/bash
set -e
set +x

. ./common

display_error()
{
    echo "Usage: "
    echo "$0 IMAGE($SEPARATED_IMAGE_NAMES)"
    exit 2
}

IMAGE=$1

if [[ ! ("${IMAGE_NAMES[@]}" =~ "$IMAGE") ]]; then
    display_error
fi

if [ $IMAGE = "raspbian" ]; then
  PACKER_COMMAND="sudo packer build -force /vagrant/packer.json"
  VAGRANT_CWD=packer/$IMAGE vagrant up
  VAGRANT_CWD=packer/$IMAGE vagrant ssh -c "$PACKER_COMMAND"
  VAGRANT_CWD=packer/$IMAGE vagrant ssh -c "sudo mv output-arm-image/image /vagrant/raspbian.img"
else
  PACKER_COMMAND="packer build -force -var-file=private_vars.json packer/$IMAGE/packer.json"
  if [ -n "$DEBUG" ]; then
    PACKER_LOG=1 $PACKER_COMMAND
  else
    $PACKER_COMMAND
  fi
fi

trap : 0
echo >&2 'Done'
