#!/bin/bash
set -e
set +x

. ./common

if [ ! -f ./private_vars_ansible.json ]; then
  echo "Private vars file does not exist at ./private_vars_ansible.json. Please create it, see private_vars_ansible.example.json for reference"
  exit 2
fi

display_error()
{
    echo "Usage: "
    echo "$0 APP($SEPARATED_APP_NAMES)"
    exit 2
}

APP=$1

if [[ ! ("${APP_NAMES[@]}" =~ "$APP") ]]; then
    display_error
fi

# Convert debug environment variable to something that ansible understands
if [ -n "$DEBUG" ]; then
    VERBOSE="-vvvv"
    export ANSIBLE_LOG_PATH=${PWD}/ansible.log
fi

export ANSIBLE_PARAMIKO_HOST_KEY_AUTO_ADD=True

# Get the python from /usr/bin/env python to support virtualenvs
ANSIBLE_SSH_PIPELINING=True ansible-playbook -i ansible/hosts ansible/${APP}/bootstrap.yml -e "@private_vars.json" -e "@private_vars_ansible.json" $VERBOSE -e 'ansible_python_interpreter="/usr/bin/env python"'

trap : 0
echo >&2 'Done'
