---

- name: Update packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Ensure /etc/sudoers.d/ubuntu file has correct permissions
  action: file path=/etc/sudoers.d/ubuntu mode=0440 state=file owner=root group=root
  tags: ubuntu

- name: Add identity key to authorized keys on host
  authorized_key: user=ubuntu key="{{ lookup('file', ssh_public_key_path) }}"

- name: Disable password login
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"
  notify: restart sshd

- name: Disable remote root login
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PermitRootLogin" line="PermitRootLogin no"
  notify: restart sshd