---

- name: Disable local login for the david user
  user:
    name: 'david'
    password: '!'

- name: Enable rc-local
  command: systemctl enable rc-local.service

- name: Replace rc.local
  copy:
    src: rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 0755
    force: yes
