---

- name: Copy nginx configs
  template: src="{{ item }}.conf" dest="/etc/nginx/conf.d/{{ item }}.conf"
  with_items:
    - torrent
    - torrent_private
    - usenet
    - tv
    - movies
    - network
  notify:
    - restart nginx
