---

- name: Update vyos network configuration
  vyos_config:
    lines:
      - "set system host-name {{ router_hostname }}"
      - "set interfaces ethernet eth0 vif {{ router_vlan }} address '{{ router_ip }}'"
      - "set interfaces ethernet eth0 vif {{ router_vlan }} description 'LAN'"
    save: yes
