---

- name: Update vyos configuration
  local_action:
    module: vyos_config
    src: vyos.cfg
    save: yes
    backup: yes
    provider:
        host: "{{ inventory_hostname }}"
        username: "{{ vyos_username }}"
        ssh_keyfile: "{{ ssh_private_key_path }}"
        port: "{{ vyos_port }}"
