---

- hosts: all
  user: ubuntu
  become: yes

  roles:
    - ../../ansible/roles/base
    - ../roles/base
    - ../roles/vmtools
    - ../roles/purge

  vars:
    ssh_public_key_path: "~/.ssh/id_rsa.pub"
