---

- name: Install packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - lm-sensors
    - hddtemp
    - smartmontools
    - flashcache-utils
    - iotop
    - nload

- name: Copy /etc/modules
  copy:
    src: modules
    dest: /etc/modules
    owner: root
    group: root
    mode: 0600

- name: Replace grub configuration
  copy:
    src: grub
    dest: /etc/default/grub
    owner: root
    group: root
    mode: 0644
  notify: update grub

- name: Copy lvm config
  copy:
    src: lvm.conf
    dest: /etc/lvm/lvm.conf
    owner: root
    group: root
    mode: 0600
  notify:
    - update initramfs
    - vgscan

- name: Replace fstab
  copy:
    src: fstab
    dest: /etc/fstab
    owner: root
    group: root
    mode: 0644

- name: Replace crypttab
  copy:
    src: crypttab
    dest: /etc/crypttab
    owner: root
    group: root
    mode: 0644

- name: Copy mdadm config
  copy:
    src: mdadm.conf
    dest: /etc/mdadm/mdadm.conf
    owner: root
    group: root
    mode: 0600
  notify:
    - update initramfs
