---

- name: Add transmission ppa
  apt_repository:
    repo: ppa:transmissionbt/ppa
    state: present

- name: Add packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - nfs-common
    - transmission-cli
    - transmission-common
    - transmission-daemon

- name: Add mount to fstab
  mount: name=/mnt/Storage src="{{ storage_nfs_mount }}" fstype=nfs opts="auto,nofail,noatime,nolock,intr,tcp,actimeo=1800" state=mounted

- name: Stop transmission
  service:
    name: transmission-daemon
    state: stopped

- name: Copy Transmission configuration
  template:
    src: settings.json
    dest: /etc/transmission-daemon/settings.json
  notify:
    - restart transmission

- name: Start transmission
  service:
    name: transmission-daemon
    state: started
