---

- name: Add transmission ppa
  apt_repository:
    repo: ppa:transmissionbt/ppa
    state: present

- name: Add packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - nfs-common
    - transmission-cli
    - transmission-common
    - transmission-daemon

- name: Add mount to fstab
  mount: name=/mnt/Storage src="{{ storage_nfs_mount }}" fstype=nfs opts="auto,nofail,noatime,nolock,intr,tcp,actimeo=1800" state=mounted

- name: Disable transmission in systemd
  systemd:
    name: transmission-daemon.service
    enabled: no
    state: stopped

- name: Add transmission systemd config
  copy:
    src: transmission_startup.conf
    dest: /lib/systemd/system/transmission-daemon.path
  notify:
    - reload systemd

- name: Add transmission path in systemd
  systemd:
    name: transmission-daemon.path
    enabled: yes
    state: stopped

- name: Copy Transmission configuration
  template:
    src: settings.json
    dest: /etc/transmission-daemon/settings.json
  notify:
    - restart transmission
