---

- name: Add newer samba ppa
  apt_repository:
    repo: ppa:linux-schools/samba-latest
    state: present

- name: Install packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - samba

- name: Create groups
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - storage
    - storage_write
    - timemachine

- name: Create samba users
  user:
    name: "{{ item.key }}"
    shell: /usr/sbin/nologin
    createhome: no
  with_dict: "{{ cifs_credentials }}"
  no_log: True

- name: Set samba password for samba users
  shell: "(echo {{ item.value }}; echo {{ item.value }}) | smbpasswd -s -a {{ item.key }}"
  with_dict: "{{ cifs_credentials }}"
  no_log: True

- name: Add users to storage group
  user:
    name: "{{ item }}"
    groups: storage
    append: yes
  with_items:
    - david
    - plex
    - nzbget
    - radarr
    - sonarr
    - transmission
    - transmission-private

- name: Add users to storage_write group
  user:
    name: "{{ item }}"
    groups: storage_write
    append: yes
  with_items:
    - david
    - nzbget
    - radarr
    - sonarr
    - transmission
    - transmission-private

- name: Add users to timemachine group
  user:
    name: "{{ item }}"
    groups: timemachine
    append: yes
  with_items:
    - david

- name: Samba configuration
  copy:
    src: smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0600
  notify:
   - restart samba
