---

- name: Copy scripts
  become: yes
  copy:
    src: "{{ item }}"
    dest: "/config/scripts/{{ item }}"
    mode: a+rx
  with_items:
    - backup.sh
    - master.sh

- name: Copy template scripts
  become: yes
  template:
    src: "{{ item }}"
    dest: "/config/scripts/{{ item }}"
    mode: a+rx
  with_items:
    - dynamic_dns.sh

- name: Copy server keys
  copy:
    src: ../../openvpn-client/
    dest: /config/auth/openvpn-client

- name: Update vyos base configuration
  local_action:
    module: vyos_config
    src: vyos.cfg
    save: yes
    backup: yes
    provider:
      host: "{{ inventory_hostname }}"
      username: "vyos"
      ssh_keyfile: "{{ ssh_private_key_path }}"
      port: 22
      timeout: 60
