---

- name: Mount storage
  include_role:
    name: ../roles/mount_storage
  vars:
    read_only: yes

- name: Mount plex sync folder on storage
  include_role:
    name: ../roles/mount_storage
  vars:
    cifs_mount: "//storage.home.dmarby.se/plex"
    mount_path: "/mnt/Plex"

- name: Add plex user
  user:
    name: plex
    state: present
    createhome: no

- name: Add plexupdate systemd service
  template:
    src: "service"
    dest: "/etc/systemd/system/plexupdate.service"
    owner: root
    group: root
    mode: 0644

- name: Add systemd plexupdate timer
  template:
    src: "timer"
    dest: "/etc/systemd/system/plexupdate.timer"
    owner: root
    group: root
    mode: 0644

- name: Enable plexupdate timer
  systemd:
    daemon_reload: yes
    name: plexupdate.timer
    state: started
    enabled: yes

- name: Create plex media server path
  file:
    path: "{{ plex_path }}"
    owner: plex
    group: plex
    mode: 0744
    state: directory

- name: Add plex update configuration file
  template:
    src: "config"
    dest: "{{ plex_path }}/.plexupdate"
    owner: plex
    group: plex
    mode: 0744

- name: Download plexupdate
  git:
    repo: "{{ plexupdate_repo }}"
    dest: "{{ plexupdate_path }}"
    clone: yes
    force: yes

- name: Set plexupdate directory user
  file:
    path: "{{ plexupdate_path }}"
    owner: root
    group: root
    state: directory
    recurse: yes

- name: Run plexupdate service
  service:
    name: plexupdate
    state: restarted

- name: Create plex sync directory
  file:
    path: "/mnt/Plex/Sync+"
    owner: plex
    group: plex
    mode: 0744
    state: directory

- name: Symlink plex transcode directory
  file:
    src: "/mnt/Plex/Sync+"
    dest: "{{ plex_path }}/Library/Application Support/Plex Media Server/Cache/Transcode/Sync+"
    owner: plex
    group: plex
    mode: 0744
    state: link
  notify: restart plex
