---

- name: Install dnsutils
  apt:
    name: dnsutils
    state: present

- name: Create configuration dir
  file:
    path: /opt/coredns
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Copy configuration
  template:
    src: "{{ item }}"
    dest: "/opt/coredns/{{ item | basename }}"
    owner: root
    group: root
    mode: 0700
  with_fileglob:
    - coredns/*
  notify: restart coredns

- name: Run coredns
  docker_service:
    build: yes
    state: present
    project_name: "{{ coredns_docker_service.name }}"
    definition: "{{ coredns_docker_service.definition }}"
    debug: True
