---

- name: Install DNS server
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - bind9
    - dnsutils

- name: Enable bind9
  systemd:
    name: bind9
    daemon_reload: yes
    enabled: yes

- name: Add configs
  template:
    src: "{{ item }}"
    dest: "/etc/bind/{{ item }}"
    owner: bind
    group: bind
  notify: restart bind
  with_items:
    - named.conf.local
    - named.conf.options
    - home.dmarby.se
    - db.10
