---

- name: Add unifi apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "C0A52C50"

- name: Add the unifi apt source
  apt_repository:
    repo: "deb http://www.ubnt.com/downloads/unifi/debian stable ubiquiti"
    state: present

- name: Add mongodb apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "0C49F3730359A14518585931BC711F9BA15703C6"

- name: Add mongodb apt source
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse"
    state: present

- name: Install packages
  apt:
    name:
      - openjdk-8-jre # Unifi doesn't support newer java, and fails to install it by itself
      - mongodb-org # Install mongodb manually since we need a specific version from the 3.4 repo
      - rng-tools # Without this we run out of entropy which causes the controller to not start
    state: latest
    update_cache: yes

- name: Install unifi
  apt:
    name: "unifi"
    state: latest
    update_cache: yes

- name: Start the unifi service
  service:
    name: unifi
    state: started
