---

- name: Add the unifi apt source
  apt_repository:
    repo: "deb http://www.ubnt.com/downloads/unifi/debian stable ubiquiti"
    state: present

- name: Add unifi apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "C0A52C50"

- name: Install the unifi package
  apt:
    pkg: unifi
    state: present
    update_cache: yes

- name: Started the unifi service
  service:
    name: unifi
    state: started
