---

- name: update grub
  command: update-grub

- name: update initramfs
  command: update-initramfs -u

- name: vgscan
  command: vgscan

- name: reload sysctl
  command: /sbin/sysctl -p /etc/sysctl.d/60-flashcache.conf

- name: reload systemd
  command: systemctl daemon-reload
