---

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - build-essential
    - git
    - gcc

- name: Setup go environment
  copy:
    src: go-path.sh
    dest: /etc/profile.d

- name: Get duo-openvpn-standalone
  git:
    repo: "https://github.com/DMarby/duo-openvpn-standalone.git"
    dest: "/opt/go/src/github.com/DMarby/duo-openvpn-standalone"
    clone: yes
    update: yes

- name: Compile duo-openvpn-standalone
  shell: source /etc/profile && make && make install
  args:
    chdir: "/opt/go/src/github.com/DMarby/duo-openvpn-standalone"
    executable: /bin/bash

- name: Create duo-openvpn-standalone config
  template:
    src: config
    dest: /etc/duo-openvpn-standalone.yml
