# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/id_rsa.pub"
  config.vm.provision "file", source: "private_vars.json", destination: "/home/vagrant/private_vars.json"
  config.vm.provision "shell", :path => "scripts/provision_vm.sh", privileged: false
end
