---

- name: Update openvpn vyos configuration
  local_action:
    module: vyos_config
    src: openvpn.cfg
    save: yes
    backup: yes
    provider:
      host: "{{ inventory_hostname }}"
      username: "vyos"
      ssh_keyfile: "{{ ssh_private_key_path }}"
      port: 22
      timeout: 60
