---

- name: Install packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - iptables-persistent

- name: Set default iptables rules
  iptables_raw:
    name: default_rules
    weight: 10
    keep_unmanaged: no
    state: present
    rules: |
      -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
      -A INPUT -i lo -j ACCEPT
      -A INPUT -p icmp --icmp-type echo-request -j ACCEPT
      -A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
      -A INPUT -m state --state NEW -p tcp --dport 445 -j ACCEPT # Samba
      -A INPUT -p udp -m state --state NEW -m udp --dport 5353 -j ACCEPT # AVAHI
      -P INPUT DROP
      -P FORWARD DROP
      -P OUTPUT ACCEPT
