---

- name: Add certbot repo
  apt_repository:
    repo: ppa:certbot/certbot
    state: present

- name: Add apt packages
  apt: name="{{ item }}" state=latest update_cache=yes
  with_items:
    - certbot
    - python-pip
    - build-essential
    - openssl
    - libssl-dev

- name: Ensure the latest pip is installed
  shell: pip install --upgrade pip

- name: Add pip packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - setuptools
    - certbot-external-auth
    - requests
    - dns-lexicon

- name: Add dehydrated script
  template:
    src: dehydrated.sh
    dest: /srv/dehydrated.sh
    owner: root
    group: root
    mode: 0700

- name: Add certbot script
  template:
    src: certbot.sh
    dest: /srv/certbot.sh
    owner: root
    group: root
    mode: 0700

- name: Add cron job for certbot renewal
  cron:
    name: Certbot automatic renewal.
    job: "/srv/certbot.sh {{ item.domain }}"
    minute: "0"
    hour: "0"
    user: "root"
  with_items: "{{ certbot_domains }}"

- name: Run certbot script
  shell: "NO_NGINX_RESTART=True /srv/certbot.sh {{ item.domain }}"
  with_items: "{{ certbot_domains }}"
